Gemfile
README.md
Rakefile
lib/measures/urban_geometry_creation/measure.rb
lib/measures/urban_geometry_creation_zoning/measure.rb
lib/urbanopt/geojson/geo_file.rb
spec/tests/urbanopt/geojson/building_spec.rb
spec/tests/urbanopt/geojson/feature_spec.rb
spec/tests/urbanopt/geojson/geo_file_spec.rb
spec/tests/urbanopt/geojson/helper_spec.rb
urbanopt-geojson-gem.gemspec

Hey @karinamzalez can you review and merge this into your branch?  I made a new class [FeatureFile](https://github.com/urbanopt/urbanopt-core-gem/blob/develop/lib/urbanopt/core/feature_file.rb#L33) in urbanopt-core-gem and want GeoFile to inherit from it and override its methods

Updating to make GeoFile inherit from FeatureFile in urbanopt-core-gem

---

doc_templates/copyright_erb.txt
lib/measures/urban_geometry_creation/measure.rb
lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/feature.rb
lib/urbanopt/geojson/helper.rb
spec/tests/urbanopt/geojson/building_spec.rb
spec/tests/urbanopt/geojson/helper_spec.rb

pass in the surrounding buildings to the create_other_buildings method.

Fix surrounding buildings

---

spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/feature_spec.rb
spec/urbanopt/geojson/geo_file_spec.rb
spec/urbanopt/geojson/helper_spec.rb
spec/urbanopt/geojson/model_spec.rb
spec/urbanopt/geojson/urbanopt_geojson_spec.rb
spec/urbanopt/geojson/zoning_spec.rb

Move the tests from the tests folder into the specs folder.

Move tests

---

docs/package-lock.json

This actually addresses [docs # 8](https://github.com/urbanopt/urbanopt.github.io/issues/8), because I missed a step when I updated the `package.json` file earlier.

update package-lock file with secure dependency versions

---

.github/pull_request_template.md

Require ISSUES for PRs to address. Makes auto-changelog easy

---

Jenkinsfile

Updating CI workflow to support ruby 2.2.4 and bundler 1.x.

Update Jenkinsfile 

---

lib/urbanopt/geojson/building.rb

Added methods in Building Class to convert to hash.

Adds methods for converting building class instance to hash.

---

lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/geo_file.rb
lib/urbanopt/geojson/schema/building_properties.json
urbanopt-geojson-gem.gemspec

Fix bug that occurs when geojson has features that are not buildings
- [ X] Documentation has been modified appropriately
- [ X] An [ISSUE](https://github.com/urbanopt/urbanopt-geojson-gem/issues) has been created that this is addressing. Issues will get added to the Change Log when the change_log.rb script is run.
- [ X] This branch is up-to-date with develop

fix create_other_building functionality and merge site props to feature props

---

lib/urbanopt/geojson/building.rb
spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/helper_spec.rb
urbanopt-geojson-gem.gemspec

Sets NominalZCoordinate for building stories.

Adds nominal height for stories, test for confirming nominal height

---

urbanopt-geojson-gem.gemspec

exclude measure tests to reduce size

---

spec/urbanopt/geojson/building_spec.rb

Adds test to print geojson file footprint area/geojson gem footprint area

Adds test to check footprint area

---

lib/measures/urban_geometry_creation/measure.rb
lib/measures/urban_geometry_creation/tests/shadowed_tests.rb
lib/measures/urban_geometry_creation/tests/urban_geometry_creation_test.rb
lib/measures/urban_geometry_creation_zoning/measure.rb
lib/measures/urban_geometry_creation_zoning/tests/urban_geometry_creation_zoning_test.rb
lib/urbanopt/geojson/feature.rb
lib/urbanopt/geojson/geo_file.rb
lib/urbanopt/geojson/helper.rb
lib/urbanopt/geojson/schema/building_properties.json
lib/urbanopt/geojson/schema/electrical_connector_properties.json
lib/urbanopt/geojson/schema/electrical_junction_properties.json
lib/urbanopt/geojson/schema/thermal_connector_properties.json
lib/urbanopt/geojson/schema/thermal_junction_properties.json
spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/feature_spec.rb
spec/urbanopt/geojson/helper_spec.rb
spec/urbanopt/geojson/model_spec.rb

Fixes #105, #106, #107
Addresses issues related to ElectricalConnector and ElectricalJunction schema having incorrect names and incorrect ID URL.
Also addresses residential workflow changes that were made to remove the commercial building_type names too soon.

Schema errors

---

lib/urbanopt/geojson/schema/building_properties.json

Add:
* IECC 2006
* IECC 2009
* IECC 2012
* IECC 2015
* IECC 2018
to `templateType` field.

Add residential template type enums

---

lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/feature.rb
spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/feature_spec.rb

Adds methods and tests to calculate perimeter, aspect ratio of building footprint and determine the perimeter multiplier used as an argument for the create bar measure.

Create bar workflow

---

urbanopt-geojson-gem.gemspec

update urbanopt-geojson-gem.gemspec to use urbanopt-core 0.4.0

update urbanopt-geojson-gem.gemspec to use urbanopt-core 0.4.0

---

.github/pull_request_template.md

Changes the PR template to include keyword to automatically close the related issue when the PR is merged.

use issue-closing keyword

---

docs/package-lock.json
docs/package.json

Dependabot ini

---

lib/urbanopt/geojson/schema/building_properties.json
spec/files/nrel_stm_footprints.geojson

Adds fields for ev charging to the building properties schema.

Adds ev charging fields to building schema

---

CHANGELOG.md
Gemfile
doc_templates/copyright_js.txt
lib/urbanopt/geojson/model.rb
lib/urbanopt/geojson/region.rb
lib/urbanopt/geojson/scale_area.rb
lib/urbanopt/geojson/update_areas.rb
lib/urbanopt/geojson/validate_geojson.rb
lib/urbanopt/geojson/version.rb
lib/urbanopt/geojson/zoning.rb
spec/spec_helper.rb
spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/feature_spec.rb
spec/urbanopt/geojson/geo_file_spec.rb
spec/urbanopt/geojson/helper_spec.rb
spec/urbanopt/geojson/model_spec.rb
spec/urbanopt/geojson/urbanopt_geojson_spec.rb
spec/urbanopt/geojson/zoning_spec.rb
urbanopt-geojson-gem.gemspec

updating to ruby 2.7 and updating copyrights on missed files

---

lib/urbanopt/geojson/feature.rb

update find_feature_center method to return coordinates following the geojson order [long, lat]

update find_feature_center method to return coordinates following the geojson order [long, lat]

---

lib/urbanopt/geojson/helper.rb

Adds argument for `scaled_footprint_area` in the process other building helper method.

Fixes adjacent building shading

---

.rubocop.yml
lib/urbanopt/geojson/schema/site_properties.json

adding RNM-US fields

---

CHANGELOG.md
lib/urbanopt/geojson/schema/district_system_properties.json
lib/urbanopt/geojson/schema/electrical_connector_properties.json
lib/urbanopt/geojson/version.rb

add missing equipment and wires

---

lib/urbanopt/geojson/schema/site_properties.json

adding new field for rnm simulations

---

lib/urbanopt/geojson/schema/district_system_properties.json

adding ground-mount pv fields

---

CHANGELOG.md
Gemfile
lib/urbanopt/geojson/version.rb
urbanopt-geojson-gem.gemspec

* make sure to clean up the gemfile before merging

prep release for OS3.3

---

lib/urbanopt/geojson/schema/building_properties.json

Adds customizable templates to schema.

Adds new template to turn off appliances and modify appliance efficiency

---

lib/urbanopt/geojson/schema/building_properties.json

Restore required fields in building schema

restore required fields in building schema definition

---

.github/workflows/nightly_build.yml
README.md
spec/spec_helper.rb
urbanopt-geojson-gem.gemspec

Adds Github action to run all tests via rspec and report coverage via Coveralls. Syntax is copied from example-geojson-project.

GitHub action coveralls

---

lib/urbanopt/geojson/schema/district_system_properties.json
spec/files/example_project_combine_GHE.json
spec/files/example_project_combine_GHE_2.json
spec/urbanopt/geojson/geo_file_spec.rb

- Adds `Ground Heat Exchanger` as a district system type
- Adds Example Feature Files showing GHE network configuration and tests

Adds ground heat exchange as a district system type

---

spec/files/example_project_combine_GHE.json
spec/files/example_project_combine_GHE_2.json

- Uses single line segments for pipes in GHE network
- Maintains correct order of connecting buildings and GHE in the district loop

Fix: Update Ground Heat Exchanger Example files

---

lib/urbanopt/geojson/schema/district_system_properties.json
lib/urbanopt/geojson/schema/thermal_junction_properties.json
spec/files/example_project_combine_GHE.json
spec/files/example_project_combine_GHE_2.json

- adds start loop property to thermal junction schema
- adds start loop property to GHE example feature files

Adds `start loop` property for thermal junction

---

lib/urbanopt/geojson/schema/thermal_connector_properties.json
lib/urbanopt/geojson/schema/thermal_junction_properties.json
spec/files/example_project_with_ghe.json
spec/urbanopt/geojson/geo_file_spec.rb

- Edits required properties in the schema

modify connectors and junctions schema

---

spec/urbanopt/geojson/geo_file_spec.rb

Somehow my [tests PR](https://github.com/urbanopt/urbanopt-geojson-gem/pull/248) didn't merge this properly so the path didn't read properly. All better now.

this fixes a test that didn't get merged properly in the tests PR

---

Gemfile

Fixing https://github.com/urbanopt/urbanopt-geojson-gem/issues/276.

Fixed(?) the regexp and core issue.

---

.github/workflows/nightly_build.yml
CHANGELOG.md
Gemfile
lib/measures/urban_geometry_creation/LICENSE.md
lib/measures/urban_geometry_creation/README.md
lib/measures/urban_geometry_creation/measure.xml
lib/measures/urban_geometry_creation_zoning/LICENSE.md
lib/measures/urban_geometry_creation_zoning/README.md
lib/measures/urban_geometry_creation_zoning/measure.xml
lib/urbanopt/geojson/version.rb
urbanopt-geojson-gem.gemspec

New gem versions to go with OS 3.10

Update for OS 3.10

---

.github/workflows/nightly_build.yml
CHANGELOG.md
Gemfile
lib/measures/urban_geometry_creation/LICENSE.md
lib/measures/urban_geometry_creation/README.md
lib/measures/urban_geometry_creation/measure.xml
lib/measures/urban_geometry_creation_zoning/LICENSE.md
lib/measures/urban_geometry_creation_zoning/README.md
lib/measures/urban_geometry_creation_zoning/measure.xml
lib/urbanopt/geojson/version.rb
urbanopt-geojson-gem.gemspec

* call specific branches of dependencies in Gemfile
* remove dependency on released version of core-gem
* bump patch version to v1.0.2 for this fix
* use released bcl with ext-gem branch
* use released versions of gems for os3.10
* temp: add rubocop while testing
* update measures with `openstudio:update_measures` rake task
* use updated dev dependencies for extension-gem v0.9
* use OS3.10 in CI
* prep v1.1.0
---------
[description here]

merge v1.1.0 into master
