docs/package.json

Upgrade package versions to close security holes identified by GitHub.
This addresses [docs issue # 8](https://github.com/urbanopt/urbanopt.github.io/issues/8)

update package versions to fix security holes identified by github

---

Gemfile
urbanopt-geojson-gem.gemspec

Use version 0.1.5 of openstudio-extension-gem https://github.com/NREL/openstudio-extension-gem/releases/tag/v0.1.5

Use new version of extension gem

---

urbanopt-geojson-gem.gemspec

Require ruby < 2.3.0

---

RDOC_MAIN.md
README.md
lib/measures/urban_geometry_creation/tests/urban_geometry_creation_test.rb
lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/helper.rb

The shading surfaces for other building were created incorrectly. They were created using the first building footprint but with the other building height. This was happening because the check to ensure the current building is skipped while creating other buildings was not working correctly, and also the instance variable @feature_json which stores the other building feature was not getting updated as each other building was looped through. 
The check to skip current building while checking for shading due to other buildings is updated and an additional argument is added in the create_space_per_building method to ensure the correct feature json is passed while creating other building.

Fixes bug while creating shading surface for adjacent buildings.

---

lib/urbanopt/geojson/geo_file.rb

Instead of pulling site-level properties (climate_zone, weather_file, etc.) from the site origin feature, look for the information in the project hash of the geojson file.  site origin feature is more closely related to the internal UI...project hash is more flexible for other UIs

look for site features in project key instead of Site Origin feature

---

lib/urbanopt/geojson/schema/electrical_junction_properties.json

* fix for opendss workflow... I think we can safety make this optional since the enum only has 1 thing in it.

make connector-type optional on electrical junction

---

docs/package.json

Add minimist and dot-prop to dev dependencies, so we can set minimum version levels

bump minimist and dot-prop versions

---

lib/urbanopt/geojson/schema/electrical_connector_properties.json

Fix connector_type on ElectricalConnector Schema to match UI.  Option should be "Wire" instead of "Line"

switch Line to Wire on connector_type

---

docs/.vuepress/components/InnerJsonSchema.vue
docs/.vuepress/config.js
docs/.vuepress/highlight.js
docs/.vuepress/json-schema-deref-loader.js
docs/package-lock.json

json-schema-ref-parser doesn't ship with a version compiled for browsers. I
fought for a bit to try and include it in our webpack config, but that didn't
seem to work. Instead, I found an issue https://github.com/APIDevTools/json-schema-ref-parser/issues/192
where someone had turned it into a webpack loader that runs on the schemas at import time.
That seems to have done the trick, and it compiles now.
I also had to change a path for hljs.
[description here]

Fix vuepress compile

---

lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/feature.rb
lib/urbanopt/geojson/geo_file.rb
lib/urbanopt/geojson/scale_area.rb
spec/files/nrel_stm_footprints.geojson
spec/urbanopt/geojson/geo_file_spec.rb

Fixes bug while checking for empty property in merge_site_properties method.

Fix bug while checking for empty properties

---

lib/urbanopt/geojson/feature.rb

Fixed longitude, latitude input when calculating the feature center (long,lat).

fix longitude, latitude input when calculating the feature's center(long,lat)

---

LICENSE.md
lib/measures/urban_geometry_creation/measure.xml
lib/measures/urban_geometry_creation_zoning/measure.xml
lib/measures/urban_geometry_creation_zoning/tests/OV_Buildings_Update_090420_res_eui_test.json
lib/measures/urban_geometry_creation_zoning/tests/example_project_combined.json
lib/urbanopt/geojson/helper.rb
lib/urbanopt/geojson/model.rb
lib/urbanopt/geojson/region.rb
lib/urbanopt/geojson/scale_area.rb
lib/urbanopt/geojson/update_areas.rb
lib/urbanopt/geojson/validate_geojson.rb
lib/urbanopt/geojson/version.rb
lib/urbanopt/geojson/zoning.rb
spec/spec_helper.rb
spec/urbanopt/geojson/building_spec.rb
spec/urbanopt/geojson/feature_spec.rb
spec/urbanopt/geojson/geo_file_spec.rb
spec/urbanopt/geojson/helper_spec.rb
spec/urbanopt/geojson/model_spec.rb
spec/urbanopt/geojson/urbanopt_geojson_spec.rb
spec/urbanopt/geojson/zoning_spec.rb

Changes elevation angle used in determining whether the adjacent building is shading the main building.

Adjacent shading updates

---

lib/urbanopt/geojson/schema/building_properties.json

Adds additional field to schema

Ev charging

---

.github/workflows/nightly_build.yml

Use OpenStudio 3.5.1 in GHA CI

update gha ci to openstudio 3.5.1

---

lib/urbanopt/geojson/schema/thermal_connector_properties.json
lib/urbanopt/geojson/schema/thermal_junction_properties.json

A few typos were made in the schema:
1. Thermal Connector start_id should be in CamelCase
2. Thermal Junction should have a junction_id instead of a connector_id

fix schema typos

---

spec/files/example_project_combine_GHE_2.json

- Adds District System Type property for GHE. 
- This is used in the GMT to add GHE specific properties in the system parameter file.

add district system type

---

urbanopt-geojson-gem.gemspec

This appears to have caused a dependency conflict with openstudio-standards

downgrade json-schema to 2.7

---

lib/urbanopt/geojson/schema/site_properties.json

Also allow `null` for a few more optional fields.
The internal UI was generating invalid geojson files, because `null` wasn't allowed in the schema. Now it's ok.

Allow null for some optional fields

---

lib/urbanopt/geojson/building.rb
lib/urbanopt/geojson/geo_file.rb
lib/urbanopt/geojson/schema/building_properties.json
lib/urbanopt/geojson/schema/site_properties.json

Added UO restock connection inputs to the site schema

Added UO-ResStock connection variable to the site properties schema

---

.gitignore
lib/urbanopt/geojson/schema/thermal_junction_properties.json
spec/files/example_project_combine_GHE.json
spec/files/example_project_combine_GHE_2.json

This setting needed to be manually set in the geojson file, and it needed to be on the correct ThermalJunction. I figured out a way to remove it altogether [in ThermalNetwork](https://github.com/NREL/ThermalNetwork/pull/58), so here I'm removing it from the schema (and test files) so it doesn't accidentally get used.

Remove `is_ghe_start_loop` from schema

---

CHANGELOG.md
lib/urbanopt/geojson/schema/electrical_connector_properties.json
lib/urbanopt/geojson/schema/thermal_connector_properties.json
lib/urbanopt/geojson/version.rb
spec/files/example_project_combine_GHE.json
spec/files/example_project_combine_GHE_2.json
spec/files/example_project_with_ghe.json

We were using IP units for connector lengths, which was surprising and not in accordance with E+/OS standard usage. This changes the wording in the schema for those components.
Electrical connectors are staying in IP units, at least temporarily, due to the connection to other packages (rnm, opendss, ditto, etc) so we can evaluate the impacts of changing to SI units.

Use SI units for connector lengths

---

urbanopt-geojson-gem.gemspec

This [is required](https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/.rubocop.yml#L6) by rubycop config. Previous versions inherited rubocop sub-dependencies through extension-gem (IIRC) that we now have to explicitly provide in each gem.

Add `rubocop-performance` dev dependency
